<a href="https://colab.research.google.com/github/Heerthihaa/CODSOFT-TASK/blob/main/Untitled10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn import model_selection
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [4]:
df=pd.read_csv("/content/train-data.csv")
df=pd.read_csv("/content/test-data.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/train-data.csv'

In [18]:
print(train_data.shape)

(6019, 14)

In [19]:
print(test_data.shape)

(1234, 13)

In [20]:
train_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [21]:
train_data.describe()

        Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  6019.000000  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   3009.000000  2013.358199       5.873838e+04     5.278735     9.479468
std    1737.679967     3.269742       9.126884e+04     0.808840    11.187917
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1504.500000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3009.000000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.500000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [22]:
train_data.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [23]:
df = df.dropna()

In [24]:
df = df.dropna(axis=1)

In [26]:
train_data['is_train'] = 1  # Label as train
test_data['is_train'] = 0   # Label as test

# Now combine the datasets
combined_data = pd.concat([train_data, test_data], axis=0).reset_index(drop=True)

In [27]:
# Apply preprocessing to 'combined_data' as needed, then split it back
train_data = combined_data[combined_data['is_train'] == 1].drop('is_train', axis=1)
test_data = combined_data[combined_data['is_train'] == 0].drop('is_train', axis=1)

In [2]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
# Combine data
combined_data = pd.concat([train_data, test_data], axis=0).reset_index(drop=True)

# Apply scaling
scaler = StandardScaler()
combined_data_scaled = scaler.fit_transform(combined_data.drop('is_train', axis=1))

# Convert back to DataFrame and reattach is_train column
combined_data_scaled = pd.DataFrame(combined_data_scaled, columns=combined_data.columns[:-1])
combined_data_scaled['is_train'] = combined_data['is_train']

# Split back into train and test
train_data_scaled = combined_data_scaled[combined_data_scaled['is_train'] == 1].drop('is_train', axis=1)
test_data_scaled = combined_data_scaled[combined_data_scaled['is_train'] == 0].drop('is_train', axis=1)

NameError: name 'train_data' is not defined

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

In [ ]:
data = pd.read_csv('your_data.csv')  # Replace 'your_data.csv' with your file path

# Assume 'target' is the column to predict and all other columns are features
X = data.drop('target', axis=1)  # Features
y = data['target']